# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301c55fa530d105a9acc273ca6967e9fe54fff53a9833ff326d5d93b04087fb67c3250e61e01ec992591a6e980798035c1209ab3c464a0c680d630ef0d411306

test:
  secret_key_base: 977d7b92ffeed44b77105a8404cd978e8a5bc233a1385a6c143f0857e9261c0d63e233e536d268bd940dfdcfbcbcc7df798bf3f69983332f03056a828fec6fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
